### ISSUE TITLE
ipirat_isInstalled Local Storage key

### ISSUE THREAD

**Issue by JasperV** [better-history/better-history#331]
Why does the plugin add the ipirat_isInstalled key to my Local Storage?

**Comment by lenovouser** [comment]
@JasperV #330

**Comment by JasperV** [comment]
Thanks

**Comment by stuartpb** [comment]
If you want to remove this key from all the sites you've visited that use Local Storage, I wrote https://github.com/stuartpb/corexit to clean it up.

Warning: not recommended if you have many sites in your browser history (the script chokes in a LOT of different scenarios).
